// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdbnesladhtgunpryzzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkYm5lc2xhZGh0Z3VucHJ5enpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTg1MDIsImV4cCI6MjA1OTEzNDUwMn0.1II3BRsOeMWy_s4wlXqfQhh_9BWD4xmHu4JgoIImR94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);